#!/usr/bin/env python
class Problem2:
    """ Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
    the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
    even-valued terms.
    https://projecteuler.net/problem=2
    """
    def solution(self):
        return sum([x for x in self.fibo(4000000) if not x % 2])

    def fibo(self, limit):
        a,b = 1,2
        yield a
        yield b
        while b <= limit:
            a, b = b, a + b
            yield b

    def isOK(self):
        '''Test that solution returns the valid value'''
        return self.solution() == 4613732
