#!/usr/bin/env python
class Problem2:
    """ Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
    the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
    even-valued terms.
    https://projecteuler.net/problem=2
    """
    def solution(self):
        print (self.fibo(10))

    def fibo(self, x):
        if x < 1:
            return 0
        if x == 1:
            return 1
        return self.fibo(x - 1)  + self.fibo(x - 2)

    def isOK(self):
        return False
